project:
  type: website

website:
  title: "Naomi Suzuki"
  navbar:
    right:
      - href: index.qmd
        text: Home
      - about.qmd
      - href: projects.qmd
        text: Projects

format:
  html:
    theme: pulse
    css: styles.css
    toc: true

editor: visual

execute:
  freeze: auto

